### ISSUE TITLE
"Error: fetch failed" on node 18 behind corporate proxy

### ISSUE THREAD

**Issue by pfei5** [nrwl/nx-set-shas#113]
I upgraded my pipeline to use node 18.17.1. With that upgrade I get an error "Error: fetch failed". (see screenshot below).
Downgrading to node 16 resolves that error.

My pipeline runs behind a corporate proxy server.

My wild guess for what might be happening is this:
Node 18 [introduced a global fetch api.](https://nodejs.org/de/blog/announcements/v18-release-announce#fetch-experimental)
I'm guessing that the http client falls back to using that native fetch api when it's available, without honoring the proxy settings.

<img width="1560" alt="nrwl:nx-set-shas" src="https://github.com/nrwl/nx-set-shas/assets/79921672/b6a7105f-b9c6-45ac-a575-262accf06ecc">

**Comment by meeroslav** [comment]
Lucky coincidence, this should be fixing that: https://github.com/nrwl/nx-set-shas/pull/106

Can you double-check, please? The version `3.3` updated repo to Node v18 and bumps the version of octokit dependencies (which require v18) so hopefully that should solve it.

**Comment by pfei5** [comment]
@meeroslav  works like a charm! Thank you very much!

**Comment by dekkofilms** [comment]
@meeroslav should that version bump requirement have been a major version bump rather than a minor version? It has recently caused some failures in our CI process.

**Comment by meeroslav** [comment]
This in particular was tested on Node 14 and works the same way as it does on v18. Initially we wanted to make it a major version (v4) but after testing we bumped it down to just minor.

**Comment by dekkofilms** [comment]
@meeroslav interesting ... we are on node 14 and it does not work. we had to pin everything to `3.2.2` and the problem was resolved.

**Comment by meeroslav** [comment]
@dekkofilms can you create a new issue and report what error you get?

I tested with two of our repos and didn't encounter any issues.
