### ISSUE TITLE
Not able to execute the Nx set sha action

### ISSUE THREAD

**Issue by mauriziovitale** [nrwl/nx-set-shas#115]
Since this morning we are getting the following error: 

Run nrwl/nx-set-shas@v3
Run node "$GITHUB_ACTION_PATH/dist/index.js" "$gh_token" "$main_branch_name" "$error_on_no_successful_workflow" "$last_successful_event" "$working_directory" "$working_id"
/home/runner/work/_actions/nrwl/nx-set-shas/v3/dist/index.js:2140
  static {
         ^

SyntaxError: Unexpected token '{'
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47
Error: Process completed with exit code 1.

I have the feeling a recent patch is causing the issue, most probably 
https://github.com/nrwl/nx-set-shas/commit/0712662561b193586e4f5db91b21c638285c9f4d

@meeroslav

**Comment by mlitvinav** [comment]
Seems something is broken in the latest patch version v3.0.1. Downgrading to the previous working version v3.0.0 fixes the previously mentioned problem.

Here is my action usage if you look for a quick fix:
```
      - name: detect affected
         uses: nrwl/nx-set-shas@v3.0.0
```

**Comment by mauriziovitale** [comment]
I think the last patch is forcing to use node 18
https://github.com/nrwl/nx-set-shas/releases/tag/v3

I was already using an "old" version but now is not working, and I guess because we are not using node 18 yet

**Comment by mauriziovitale** [comment]
Lesson learnt ... never use tag version for gh action but always pin sha :) 

nrwl/nx-set-shas@8b116da380aced2121ab9ee569d2927a6661b3e9

works as expected

**Comment by meeroslav** [comment]
The issue is in the Octokit version 6. I will downgrade to v5.

**Comment by meeroslav** [comment]
@mauriziovitale, which node version are you using?

**Comment by mauriziovitale** [comment]
@meeroslav       node-version: 14.15.4

**Comment by hylle** [comment]
> Node 18 is now LTS and Node 16 will be unsupported in a few days, so there is no point in using anything below v18 at the moment.

@meeroslav Either way an upgrade requiring a higher new node version should probably be a major bump to the action.

**Comment by mauriziovitale** [comment]
I agree with @hylle if your are following semantic version u should bump and u should not change the version already deployed with a breaking change.
