### ISSUE TITLE
Error: `Failed to determine PR number` when using a merge queue on non-main branch

### ISSUE THREAD

**Issue by tom-sherman** [nrwl/nx-set-shas#120]
The regex that infers the PR number from the ref is slightly wrong, it assumes the merge queue is named the main branch. I believe this can be the case for a variety of reasons (custom merge groups) but for us it came up when using a merge group on a different branch other than `main`.

https://github.com/nrwl/nx-set-shas/blob/0e2d18b530b83b68263ff7b74e46b1ba300c83fc/find-successful-workflow.ts#L137

Our ref was `gh-readonly-queue/some-branch-name/pr-108-shaXXX`, the main branch was `main`. So the regex didn't match.

Maybe this data can be inferred via an API call or from the event payload?

**Comment by meeroslav** [comment]
This is not something we can infer automatically. We suggest to create a new workflow/job for different "main" branches.

**Comment by tom-sherman** [comment]
@meeroslav is nx-set-shas supposed to work in general when merging into a non-main branch? It should just compare against main all the time right?

If so, I'd expect this same behaviour for merge queues.

My suggestion here is to improve the heuristic to handle this case - there have been some assumptions made about the merge queue that are incorrect.
