### ISSUE TITLE
Unexpected Diff SHAs for merge queues using v4 

### ISSUE THREAD

**Issue by Fitzbert-Fitz** [nrwl/nx-set-shas#128]
Hi there,

I already looked into #100 but I do not see the behaviour I would expect. I am using nrwl/nx-set-shas@v4.

For an open PR I see the expected behaviour:
since all builds on main were successfull the nx-set-shas returns head=1b96db0 and base=cb63505  (orange in picture)
![image](https://github.com/nrwl/nx-set-shas/assets/62591134/095960dc-c10e-4f5a-b807-e054a96e6653)

Adding the PR to the merge queue leads to unexpected behaviour:
nx-set-shas now returns head=840c8b9 (expected) and base=e137e9b where I would expect base=cb63505
![image](https://github.com/nrwl/nx-set-shas/assets/62591134/689c37fe-994a-4cd2-93ff-3b0d829e24f7)

Is my expectation wrong? The shown example leads to NX including a lot more changes for the merge queue.

I do not know it hte github actions logs are helpful. The shas are different from the ones in the pictures.
<details>
<summary>Click to expand the logs</summary>
##[debug]Evaluating condition for step: 'Derive appropriate SHAs for base and head for `nx affected` commands'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Derive appropriate SHAs for base and head for `nx affected` commands
##[debug]Loading inputs
##[debug]Loading env
Run nrwl/nx-set-shas@v4
##[debug]Evaluating: github.token
##[debug]Evaluating Index:
##[debug]..Evaluating github:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'token'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Evaluating: inputs.main-branch-name
##[debug]Evaluating Index:
##[debug]..Evaluating inputs:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'main-branch-name'
##[debug]=> 'main'
##[debug]Result: 'main'
##[debug]Evaluating: inputs.error-on-no-successful-workflow
##[debug]Evaluating Index:
##[debug]..Evaluating inputs:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'error-on-no-successful-workflow'
##[debug]=> 'false'
##[debug]Result: 'false'
##[debug]Evaluating: inputs.last-successful-event
##[debug]Evaluating Index:
##[debug]..Evaluating inputs:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'last-successful-event'
##[debug]=> 'push'
##[debug]Result: 'push'
##[debug]Evaluating: inputs.working-directory
##[debug]Evaluating Index:
##[debug]..Evaluating inputs:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'working-directory'
##[debug]=> '.'
##[debug]Result: '.'
##[debug]Evaluating: inputs.workflow-id
##[debug]Evaluating Index:
##[debug]..Evaluating inputs:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'workflow-id'
##[debug]=> ''
##[debug]Result: ''
##[debug]Evaluating condition for step: 'run'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: run
##[debug]Loading inputs
##[debug]Loading env
Run node "$GITHUB_ACTION_PATH/dist/index.js" "$gh_token" "$main_branch_name" "$error_on_no_successful_workflow" "$last_successful_event" "$working_directory" "$working_id"
##[debug]/usr/bin/bash --noprofile --norc -e -o pipefail /runner/_work/_temp/903c52ac-16ee-4207-adc0-de9ad3a985fd.sh

Found PR #1318 from merge queue branch
##[debug]Set output base = 8f7d2a28a49537c5d51722e3f6bcbc951d9171f5
##[debug]Set output head = a8ab0329bffa62256b164b3c39a1651843071310
##[debug]Finished: run
##[debug]Evaluating condition for step: 'run'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: run
##[debug]Loading inputs
##[debug]Evaluating: format('echo "Base SHA"
##[debug]echo {0}
##[debug]echo ""
##[debug]echo "Head SHA"
##[debug]echo {1}
##[debug]echo ""
##[debug]', steps.setSHAs.outputs.base, steps.setSHAs.outputs.head)
##[debug]Evaluating format:
##[debug]..Evaluating String:
##[debug]..=> 'echo "Base SHA"
##[debug]echo {0}
##[debug]echo ""
##[debug]echo "Head SHA"
##[debug]echo {1}
##[debug]echo ""
##[debug]'
##[debug]..Evaluating Index:
##[debug]....Evaluating Index:
##[debug]......Evaluating Index:
##[debug]........Evaluating steps:
##[debug]........=> Object
##[debug]........Evaluating String:
##[debug]........=> 'setSHAs'
##[debug]......=> Object
##[debug]......Evaluating String:
##[debug]......=> 'outputs'
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'base'
##[debug]..=> '8f7d2a28a49537c5d51722e3f6bcbc951d9171f5'
##[debug]..Evaluating Index:
##[debug]....Evaluating Index:
##[debug]......Evaluating Index:
##[debug]........Evaluating steps:
##[debug]........=> Object
##[debug]........Evaluating String:
##[debug]........=> 'setSHAs'
##[debug]......=> Object
##[debug]......Evaluating String:
##[debug]......=> 'outputs'
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'head'
##[debug]..=> 'a8ab0329bffa62256b164b3c39a1651843071310'
##[debug]=> 'echo "Base SHA"
##[debug]echo 8f7d2a28a49537c5d51722e3f6bcbc951d9171f5
##[debug]echo ""
##[debug]echo "Head SHA"
##[debug]echo a8ab0329bffa62256b164b3c39a1651843071310
##[debug]echo ""
##[debug]'
##[debug]Result: 'echo "Base SHA"
##[debug]echo 8f7d2a28a49537c5d51722e3f6bcbc951d9171f5
##[debug]echo ""
##[debug]echo "Head SHA"
##[debug]echo a8ab0329bffa62256b164b3c39a1651843071310
##[debug]echo ""
##[debug]'
##[debug]Loading env
Run echo "Base SHA"
##[debug]/usr/bin/bash --noprofile --norc -e -o pipefail /runner/_work/_temp/0c4c778c-eead-4bda-97d8-bf70abd0a46b.sh
Base SHA
8f7d2a28a49537c5d51722e3f6bcbc951d9171f5

Head SHA
a8ab0329bffa62256b164b3c39a1651843071310

##[debug]Finished: run
##[debug]Evaluating condition for step: 'run'
##[debug]Evaluating: (success() && (inputs.set-environment-variables-for-job == 'true'))
##[debug]Evaluating And:
##[debug]..Evaluating success:
##[debug]..=> true
##[debug]..Evaluating Equal:
##[debug]....Evaluating Index:
##[debug]......Evaluating inputs:
##[debug]......=> Object
##[debug]......Evaluating String:
##[debug]......=> 'set-environment-variables-for-job'
##[debug]....=> 'true'
##[debug]....Evaluating String:
##[debug]....=> 'true'
##[debug]..=> true
##[debug]=> true
##[debug]Expanded: (true && ('true' == 'true'))
##[debug]Result: true
##[debug]Starting: run
##[debug]Loading inputs
##[debug]Evaluating: format('echo "NX_BASE={0}" >> $GITHUB_ENV
##[debug]echo "NX_HEAD={1}" >> $GITHUB_ENV
##[debug]echo "NX_BASE and NX_HEAD environment variables have been set for the current Job"
##[debug]', steps.setSHAs.outputs.base, steps.setSHAs.outputs.head)
##[debug]Evaluating format:
##[debug]..Evaluating String:
##[debug]..=> 'echo "NX_BASE={0}" >> $GITHUB_ENV
##[debug]echo "NX_HEAD={1}" >> $GITHUB_ENV
##[debug]echo "NX_BASE and NX_HEAD environment variables have been set for the current Job"
##[debug]'
##[debug]..Evaluating Index:
##[debug]....Evaluating Index:
##[debug]......Evaluating Index:
##[debug]........Evaluating steps:
##[debug]........=> Object
##[debug]........Evaluating String:
##[debug]........=> 'setSHAs'
##[debug]......=> Object
##[debug]......Evaluating String:
##[debug]......=> 'outputs'
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'base'
##[debug]..=> '8f7d2a28a49537c5d51722e3f6bcbc951d9171f5'
##[debug]..Evaluating Index:
##[debug]....Evaluating Index:
##[debug]......Evaluating Index:
##[debug]........Evaluating steps:
##[debug]........=> Object
##[debug]........Evaluating String:
##[debug]........=> 'setSHAs'
##[debug]......=> Object
##[debug]......Evaluating String:
##[debug]......=> 'outputs'
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'head'
##[debug]..=> 'a8ab0329bffa62256b164b3c39a1651843071310'
##[debug]=> 'echo "NX_BASE=8f7d2a28a49537c5d51722e3f6bcbc951d9171f5" >> $GITHUB_ENV
##[debug]echo "NX_HEAD=a8ab0329bffa62256b164b3c39a1651843071310" >> $GITHUB_ENV
##[debug]echo "NX_BASE and NX_HEAD environment variables have been set for the current Job"
##[debug]'
##[debug]Result: 'echo "NX_BASE=8f7d2a28a49537c5d51722e3f6bcbc951d9171f5" >> $GITHUB_ENV
##[debug]echo "NX_HEAD=a8ab0329bffa62256b164b3c39a1651843071310" >> $GITHUB_ENV
##[debug]echo "NX_BASE and NX_HEAD environment variables have been set for the current Job"
##[debug]'
##[debug]Loading env
Run echo "NX_BASE=8f7d2a28a49537c5d51722e3f6bcbc951d9171f5" >> $GITHUB_ENV
##[debug]/usr/bin/bash --noprofile --norc -e -o pipefail /runner/_work/_temp/2fb2af3d-ad75-4024-8caf-cb445bfdad40.sh
NX_BASE and NX_HEAD environment variables have been set for the current Job
##[debug]NX_BASE='8f7d2a28a49537c5d51722e3f6bcbc951d9171f5'
##[debug]NX_HEAD='a8ab0329bffa62256b164b3c39a1651843071310'
##[debug]Finished: run
##[debug]Evaluating: steps.setSHAs.outputs.base
##[debug]Evaluating Index:
##[debug]..Evaluating Index:
##[debug]....Evaluating Index:
##[debug]......Evaluating steps:
##[debug]......=> Object
##[debug]......Evaluating String:
##[debug]......=> 'setSHAs'
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'outputs'
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'base'
##[debug]=> '8f7d2a28a49537c5d51722e3f6bcbc951d9171f5'
##[debug]Result: '8f7d2a28a49537c5d51722e3f6bcbc951d9171f5'
##[debug]Evaluating: steps.setSHAs.outputs.head
##[debug]Evaluating Index:
##[debug]..Evaluating Index:
##[debug]....Evaluating Index:
##[debug]......Evaluating steps:
##[debug]......=> Object
##[debug]......Evaluating String:
##[debug]......=> 'setSHAs'
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'outputs'
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'head'
##[debug]=> 'a8ab0329bffa62256b164b3c39a1651843071310'
##[debug]Result: 'a8ab0329bffa62256b164b3c39a1651843071310'
##[debug]Evaluating: steps.setSHAs.outputs.noPreviousBuild
##[debug]Evaluating Index:
##[debug]..Evaluating Index:
##[debug]....Evaluating Index:
##[debug]......Evaluating steps:
##[debug]......=> Object
##[debug]......Evaluating String:
##[debug]......=> 'setSHAs'
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'outputs'
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'noPreviousBuild'
##[debug]=> null
##[debug]Result: null
##[debug]Finishing: Derive appropriate SHAs for base and head for `nx affected` commands

</details>

**Comment by meeroslav** [comment]
I think this is expected behavior for the merge queues. 

The PRs your commit is related to the branching point from the `main` (I believe this is not shown correctly on your diagram since `cb63505` should have been the branching SHA for the feature branch).

The merge queue assures your commit is compatible with the latest `main`, not the historical branching point, so it checks against the latest successful SHA on `main`. 

If it would return the same SHA as the standard `PR` workflow, then there wouldn't be a point in using it.

**Comment by kdawgwilk** [comment]
I think where this gets tricky is when you have multiple batches queued up.  You can set merge queues up to merge multiple commits in a single merge as a group when setting the merge limit max > 1 or if you want gitlab esque merge trains you can set merge limit max = 1.  I think the BASE_SHA should be set to the first commit in your group.

**Comment by joemckie** [comment]
Hi @meeroslav, I'm experiencing the exact opposite of what you've described in your comment, with the `merge_group` event testing against the historical branching point, which is often multiple, fully tested merges to `main` in the past. Any idea why this would be the case?
