### ISSUE TITLE
Add cwd to input parameters

### ISSUE THREAD

**Issue by maximblack** [nrwl/nx-set-shas#13]
The local path to the directory where the repository is located
Useful when there are multiple repositories in different folders

**Comment by meeroslav** [comment]
Hi @maximblack, thank you for the feature request.

Do you mind explaining the use cases a bit more? The `nx-set-shas` is meant to run on a single monorepo repository. Depending on your selected docker-machine, your repository is usually at the `~/repo` folder.

**Comment by maximblack** [comment]
> Hi @maximblack, thank you for the feature request.
> 
> Do you mind explaining the use cases a bit more? The `nx-set-shas` is meant to run on a single monorepo repository. Depending on your selected docker-machine, your repository is usually at the `~/repo` folder.

Hi, based on my use case, I'm working with 2 repositories (1 monorepo + gitops) in the same workflow. I would like to split them into different paths. Currently, this is impossible with `nx-set-shas`

**Comment by meeroslav** [comment]
Hi, sorry for the delay. So if I understand correctly, you have something like this:

```yaml
main git repository:
   nx-repo:
   gitops:
```

And you'd like to run `nx-set-shas` only on the commits that modified the nx repo, but not gitops?
If that is the case, I'm not sure whether implementing this would justify the cost. Currently, we use built-in APIs to get all commits, filter the last successful one and return the hash. To implement the `cwd` we would have to parse the commit and see which files were changed and whether they belong to the given directory.

**Comment by maximblack** [comment]
> Hi, sorry for the delay. So if I understand correctly, you have something like this:
> 
> ```yaml
> main git repository:
>    nx-repo:
>    gitops:
> ```
> 
> And you'd like to run `nx-set-shas` only on the commits that modified the nx repo, but not gitops? If that is the case, I'm not sure whether implementing this would justify the cost. Currently, we use built-in APIs to get all commits, filter the last successful one and return the hash. To implement the `cwd` we would have to parse the commit and see which files were changed and whether they belong to the given directory.

Hi, no need to parse the commit (to check changed files), just need an argument to specify base working dir (not root)

Checkout action has `path` argument to specify the local directory:
https://github.com/actions/checkout

As an example the `cwd` argument in `add-and-commit` action:
https://github.com/EndBug/add-and-commit

**Comment by meeroslav** [comment]
Ok, that makes sense. Thanks for the clarification. Feel free to propose the PR to add this option.

**Comment by kitsune7** [comment]
I've been facing the same issue here. I have a custom runner for my Github action that doesn't place the repository code in the default location. If you're okay with adding an option for customizing the working directory, I created a [PR](https://github.com/nrwl/nx-set-shas/pull/27) that you can look over.

**Comment by kitsune7** [comment]
@meeroslav, I think there may have issue including this change in version 2.1.6.

<img width="1201" alt="Screen Shot 2022-03-23 at 12 51 52 PM" src="https://user-images.githubusercontent.com/1205871/159774781-c8e706bf-8569-4d0e-8bea-af19bc5c5c39.png">

It doesn't look like the changes made it into the release.

**Comment by meeroslav** [comment]
This patch realese did not contain your PR. I have rolled out a new version now - 2.2.0
