### ISSUE TITLE
Are there any breaking changes in v4.04, I have got following error

### ISSUE THREAD

**Issue by michalkotowski1** [nrwl/nx-set-shas#139]
<img width="2154" alt="image" src="https://github.com/nrwl/nx-set-shas/assets/105444851/ae7e10ba-9421-4671-8c39-9390ca9669ea">

**Comment by michalkotowski1** [comment]
Issue it seems that the same day issue is not longer occuring.
Fill free to close it.

**Comment by fourass** [comment]
How was this fixed ? I'm having the same issue :'(
