### ISSUE TITLE
fallback-sha is ignored

### ISSUE THREAD

**Issue by bperel** [nrwl/nx-set-shas#166]
I get the following error when specifying `fallback-sha`: 

```
Warning: Unexpected input(s) 'fallback-sha', valid inputs are ['main-branch-name', 'set-environment-variables-for-job', 'error-on-no-successful-workflow', 'last-successful-event', 'working-directory', 'workflow-id']
```

Indeed, `fallback-sha` is never passed to the [list of envs in https://github.com/nrwl/nx-set-shas/blob/main/action.yml](https://github.com/nrwl/nx-set-shas/blob/main/action.yml#L44)

**Comment by joh-klein** [comment]
Duplicate of #158
