### ISSUE TITLE
Support running behind proxy

### ISSUE THREAD

**Issue by papichulo** [nrwl/nx-set-shas#42]
**Background**
We are using selfhosted runners behind a proxy.

**Issue**
Calls to GitHub API is done using Octokit, which doesn't support proxy configuration by default.
See documentation
https://github.com/octokit/octokit.js#proxy-servers-nodejs-only

**Suggested solution**
nx-set-shas should either use a client which by default respect already configured proxies or support the option of configuring your own client.

**Comment by meeroslav** [comment]
Since there was no movement on this issue I will close it. I believe this scenario is too specific for the general nx-set-shas to support it.

However, we welcome any PRs should someone like to implement it.
