### ISSUE TITLE
Feature Request: Ability to select last successful workflow event

### ISSUE THREAD

**Issue by rodrigomata** [nrwl/nx-set-shas#6]
## Issue:
I'm trying to execute `nx affected` when I trigger a new release; however, the plugin fails to correctly find a successful run for the workflow id provided since it is checking only for `push` events; therefore, it checkouts out `HEAD~1` and no changes are detected, resulting in nothing getting deployed.

## Request:
Would be great to have the ability to add as a parameter the option to specify the event that we want to detect, leaving as default the push event if it is not provided.

Here's the line of code that would need to be changed:
https://github.com/nrwl/nx-set-shas/blob/f17afe25f004cf689fe46eae699d71123de43b9c/find-successful-workflow.js#L84

**Comment by rodrigomata** [comment]
I created this PR: https://github.com/nrwl/nx-set-shas/pull/7 in case you would like to add this feature.

**Comment by meeroslav** [comment]
Amazing @rodrigomata. Thank you!

I will go ahead and merge your PR.

**Comment by mrlubos** [comment]
Hey! Just noticed this field isn't documented in the main README. In fact, it's only ever mentioned in the files changed in #7. Please consider adding this field to README 🙏
