### ISSUE TITLE
Listing nrwl actions in the Github Marketplace

### ISSUE THREAD

**Issue by cylekoehler-thrivent** [nrwl/nx-set-shas#74]
Is it possible to get these actions listed in the Github Marketplace for verification? Specifically nx-set-shas. 

https://github.com/marketplace?type=actions&verification=verified_creator&query=nrwl

**Comment by meeroslav** [comment]
Thank you for the issue. We will check the procedure for verification.

**Comment by terozio** [comment]
This would be useful, for example in our company the policy is that actions from non-verified creators need to be pinned to the commit sha, which requires additional steps to keep up to date with the latest.

**Comment by Juice10** [comment]
The process seems reasonably straight forward now, not sure this was the case when this issue was opened: https://docs.github.com/en/apps/publishing-apps-to-github-marketplace/github-marketplace-overview/applying-for-publisher-verification-for-your-organization

**Comment by ericlacher** [comment]
I second this request, Company policies are restricting use of non-verified actions for us.

**Comment by ntrp** [comment]
Hello, any update here? Would be great to have this done and it does not require too much effort you your part

**Comment by ebickle** [comment]
Hi @meeroslav! I was surprised to find that nrwl wasn't in GitHub's verified creator's list given how broadly used Nx (and Lerna!) are in the open source community. Was hoping we could get an update on how the verified creator process is going!

As with others, we have stricter rules around non-verified actions so becoming verified would be a huge help. Thanks!

**Comment by JamesHenry** [comment]
The nrwl organization has been verified for quite some time:

<img width="740" alt="image" src="https://github.com/nrwl/nx-set-shas/assets/900523/7a473a05-7180-4c29-9721-89feb505b92d">

I wonder if GitHub will only count it on the actions listing if a new version is published. Trying that now in #151

**Comment by JamesHenry** [comment]
That did not help. I even delisted the action from the marketplace and republished the new version I just created, it's still the same: https://github.com/marketplace/actions/nx-set-shas

Anyone have any ideas on why it is not reflecting our verified status?

**Comment by JamesHenry** [comment]
I even enrolled us in the GitHub Developer Program as I saw another verified organization which published an action had this, and published another version, it did not help 😢

**Comment by ebickle** [comment]
@JamesHenry I reached out to my contacts at GitHub and they passed it along to the appropriate team... https://github.com/marketplace/actions/nx-set-shas shows as verified now.

I believe there are a few other nrwl/nx actions, correct? Can you publish the other actions in the marketplace (if they aren't already) and see what happens now? 😊

**Comment by JamesHenry** [comment]
Ok, thanks @ebickle!

There are no more actively maintained actions from us, no. I will close this one as it has been resolved now.

Thanks again!
