### ISSUE TITLE
Nx set-sha's breaks on windows CI runs [Module not found]

### ISSUE THREAD

**Issue by ryanbas21** [nrwl/nx-set-shas#8]
Hi,
Nx set sha's action works on ubuntu and linux CI runs but will fail on windows.

I've created a minimal reproduction here: https://github.com/ryanbas21/nx-min-repro/runs/4551218496?check_suite_focus=true

This is the exact error I get in my CI runs.

I copy and pasted the DTE workflow file from the docs essentially.

**Comment by meeroslav** [comment]
Thank you for reporting the issue @ryanbas21.

We will look into it as soon as possible.

**Comment by meeroslav** [comment]
The issue should be fixed now in version v2.1.3 with https://github.com/nrwl/nx-set-shas/pull/12
