### ISSUE TITLE
Optimizing checkout behaviour

### ISSUE THREAD

**Issue by mattfysh** [nrwl/nx-set-shas#86]
Hi there, I had a question about using `fetch-depth: 0` with the checkout action that precedes this one. If the repo is on the heavier side, does this mean the actions will run slower because the entire history needs to be checked out?

If so, are there other ways this action can determine shas, e.g. calling into the github api?

**Comment by PodStuart** [comment]
Same question. We have a repository which has gone past 3k commits with 3 teams pushing to it daily and doing a checkout with fetch depth of 0 is now taking around 20 seconds.

**Comment by meeroslav** [comment]
You can try entering some arbitrary large number instead of `0`.

The `0` means `all commits`. Depending on how many people push I would say that 100 should suffice.
