### ISSUE TITLE
Question: Does this check for previous passing builds in the current branch?

### ISSUE THREAD

**Issue by fpereira1** [nrwl/nx-set-shas#87]
Hi, love the tool! We will benefit from this since we were only using `origin/main` as a base in CI.

Question: Looking at the code, it looks like this tool doesn't look for passing builds in the current branch. It's only looking for passing builds in `origin/main`, is there a reason for this? In my mind passing builds in the current branch would be useful Thanks!

**Comment by meeroslav** [comment]
Hey @fpereira1, sorry for the delayed response.

The reason for not checking for successful builds in the branch is that when you are dealing with PRs generally, you want to make sure the PR as a whole is successful. Therefore, always comparing with the branching point is recommended. If two commits are mutually exclusive, you would anyway benefit from caching so the duration would not be any longer.

The main branch has no "branching point" so we can only compare it with the last good (successful) state.

You can probably get more info on my blog post https://blog.nrwl.io/using-nx-affected-on-ci-d3d2686295a0
