### ISSUE TITLE
Question: NX SHAs Differing When Using GitHub Merge Queues

### ISSUE THREAD

**Issue by charlieyeng** [nrwl/nx-set-shas#90]
Hi all, looking for a bit of help in understanding the nrwl/nx-set-shas@v3 command. I am attempting to utilize GitHub merge queues for our repo, but it is failing an es-lint step in our GitHub actions only for the queue and not for the PR check itself (same check different contexts). I believe its because during the nrwl/nx-set-shas@v3 step, the base SHA is incorrect. During the PR check it runs correctly like so
```
Run nrwl/nx-set-shas@v3
Run node $GITHUB_ACTION_PATH/dist/index.js *** master false push . 
Run echo "Base SHA"
Base SHA
16373432a98353a9a91592f4c46ede37a1b18330

Head SHA
2a9cc51e6d200982278e118daa02056c58a5730b

Run echo "NX_BASE=16373432a98353a9a91592f4c46ede37a1b18330" >> $GITHUB_ENV
NX_BASE and NX_HEAD environment variables have been set for the current Job 
```

but in the context of the merge queue it throws this log
```
Run nrwl/nx-set-shas@v3
Run node $GITHUB_ACTION_PATH/dist/index.js *** master false push . 

Workflow Id not provided. Using workflow '24879894'

Found the last successful workflow run on 'origin/master'
Commit: d3ed761e9507752bb7dc89ed48d1f69d954c738d
Run echo "Base SHA"
Base SHA
d3ed761e9507752bb7dc89ed48d1f69d954c738d

Head SHA
e5735be6d15751bfc3d36316adacd8ffb8393837

Run echo "NX_BASE=d3ed761e9507752bb7dc89ed48d1f69d954c738d" >> $GITHUB_ENV
NX_BASE and NX_HEAD environment variables have been set for the current Job
```
trying to resolve this discrepancy in order to move forward with the merge queues.

**Comment by WojciechMatuszewskiStedi** [comment]
I had the same issue. In my case, the reason for the discrepancy was that the Merge Queue sends a different event when the job is running as part of the Merge Queue. That event is `merge_group`.

[Looking at the code of the `find-successsful-workflow.js`, if the event name does not match the `pull_request`, the code follows a different path,](https://github.com/nrwl/nx-set-shas/blob/a89d5d812a67784a3c8ec83687f446be2d1c7e9d/find-successful-workflow.js#L29) which I'm not sure is the desired outcome for the Merge Queue case. You most likely(?) want to behave as if it was a `pull_request`.

I'm unsure if my solution is the best, but as my understanding goes, adding the `|| eventName === 'merge_group'` would make the action work as expected.

I'm happy to submit the PR, but I would rather wait for the maintainers of this package to voice their thoughts.

PS. Thank you for creating this action. It saves my team a lot of time!

**Comment by meeroslav** [comment]
Thank you @charlieyeng for reporting this issue and @WojciechMatuszewskiStedi for the solution proposal.

Seems like PR from @janeklb solves it

**Comment by meeroslav** [comment]
Resolved by https://github.com/nrwl/nx-set-shas/pull/100
